name: iotdevice-itrue-device-ui
base: core22
version: '0.1' 
summary: Device UI for Demo Purposes
description: |
  This is the main UI application for Demo purposes

grade: stable
confinement: strict

architectures:
  - build-on: riscv64


apps:
  ui-app:
    command: usr/bin/npm run dev
  ui-service:
    command: bin/http-server $SNAP/static -p 4000 --cors
    daemon: simple
    plugs:
      - network
      - network-bind
  backend:
    command: launch.sh
    daemon: simple
    plugs:
      - network
      - network-bind
      - snapd-control

parts:
  npm-deps:
    plugin: nil
    stage-snaps:
     - itrue-nodejs-riscv64/latest/edge

  ui:
    after: 
      - npm-deps
    plugin: npm
    source: app
    build-packages:
      - build-essential
    override-build: |
      craftctl default
      # Install and Build Project
      ${CRAFT_STAGE}/usr/bin/npm install
      ${CRAFT_STAGE}/usr/bin/npm run build
      mkdir -p $CRAFT_PART_INSTALL/static/
      cp -r dist/* $CRAFT_PART_INSTALL/static/
  
  http-server:
    after: 
      - npm-deps
    plugin: npm
    source: https://github.com/http-party/http-server.git
    source-tag: v14.1.0

  backend:
    plugin: python
    source: backend
    python-requirements:
      - requirements.txt
    
  python-source:
    source: backend
    plugin: dump

  launcher:
    source: bin
    plugin: dump

layout:
  /etc/npmrc:
    bind-file: $SNAP/etc/npmrc
  /usr/local:
    bind: $SNAP/usr

