name: iotdevice-device-ui
base: core22
version: '22'
summary: Device UI for Demo Purposes
description: |
  This is the main UI application for Demo purposes

grade: stable
confinement: strict

architectures:
  - build-on: arm64
  - build-on: amd64


apps:
  ui-app:
    command: bin/npm run dev
  ui-service:
    command: bin/http-server $SNAP/static -p 4000 --cors
    daemon: simple
    plugs:
      - network
      - network-bind
  backend:
    command: launch.sh
    daemon: simple
    plugs:
      - network
      - network-bind
      - snapd-control

parts:
  ui:
    plugin: npm
    npm-include-node: true
    npm-node-version: 16.15.0
    source: app
    build-packages:
      - build-essential
    override-build: |
      # install node dependencies
      craftctl default
      # Install and Build Project
      npm install
      npm run build
      mkdir -p "${CRAFT_PART_INSTALL}"/static/
      cp -r dist/* "${CRAFT_PART_INSTALL}"/static/

  http-server:
    plugin: npm
    npm-include-node: true
    npm-node-version: 16.15.0
    source: https://github.com/http-party/http-server.git
    source-tag: v14.1.0

  backend:
    plugin: python
    source: backend
    python-requirements:
      - requirements.txt

  python-source:
    source: backend
    plugin: dump

  launcher:
    source: bin
    plugin: dump
